{
 "title": "Sunpower",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "State",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "{stats=\"state\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "{energy=\"total_to_load\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bought",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "{energy=\"total_from_grid\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Generated",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "{energy=\"total_from_pv\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Power Total",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 13, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "{ac=\"total_generated_power\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{ac=\"total_grid_power\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{ac=\"total_load_power\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Solar %",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum({ac=\"total_generated_power\"}/ on(){ac=\"total_load_power\"})*100",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Solar",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 2, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum({dc=\"pv_power\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grid",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 5, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{ac=\"total_grid_power\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 3, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{stats=\"heatsink_temp\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "({batt=\"batt_temp\"}-12.5)*12+16",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Batt V",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 1, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{batt=\"voltage\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SoC",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 1, "x": 1, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{batt=\"batt_soc\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Batt Power",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 2, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{batt=\"out_power\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 5, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{ac=\"total_load_power\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 3, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{ac=\"voltage\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PV Voltage-Current",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "{dc=\"pv_voltage\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{dc=\"pv_current\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PowerInOut A",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 11, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "{ac=\"generated_power\", phase=\"A\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{ac=\"grid_power\", phase=\"A\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{ac=\"load_power\", phase=\"A\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P Load A",
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 23, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{ac=\"load_power\", phase=\"A\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P Gen A",
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 23, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{ac=\"generated_power\", phase=\"A\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PowerInOut B",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 11, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "{ac=\"generated_power\", phase=\"B\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{ac=\"grid_power\", phase=\"B\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{ac=\"load_power\", phase=\"B\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P Load B",
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 23, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{ac=\"load_power\", phase=\"B\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PV Power",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "{dc=\"pv_power\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P Gen B",
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 23, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{ac=\"generated_power\", phase=\"B\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PowerInOut C",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 11, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "{ac=\"generated_power\", phase=\"C\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{ac=\"grid_power\", phase=\"C\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{ac=\"load_power\", phase=\"C\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P Load C",
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 23, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{ac=\"load_power\", phase=\"C\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P Gen C",
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 23, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{ac=\"generated_power\", phase=\"C\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grid Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "{ac=\"voltage\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load Per Phase",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "{ac=\"load_power\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "{stats=\"heatsink_temp\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "({batt=\"batt_temp\"}-12)*6+26",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Energy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "{energy=\"total_from_grid\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{energy=\"total_from_pv\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}